### ISSUE TITLE
Panics in an ugly way if assh.yaml is not present

### ISSUE THREAD

**Issue by tdi** [moul/advanced-ssh-config#187]
Example:

```
➜  ~ assh info                                                                                                                                                              <aws:nc>
panic: open /Users/tdi/.ssh/assh.yml: no such file or directory [recovered]
        panic: open /Users/tdi/.ssh/assh.yml: no such file or directory

goroutine 1 [running]:
panic(0x423ea20, 0xc420079320)
        /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/moul/advanced-ssh-config/vendor/github.com/codegangsta/cli.HandleAction.func1(0xc42004b890)
        /private/tmp/assh-20160927-71842-9d3aw8/advanced-ssh-config-2.4.1/src/github.com/moul/advanced-ssh-config/vendor/github.com/codegangsta/cli/app.go:472 +0x29e
panic(0x423ea20, 0xc420079320)
        /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/moul/advanced-ssh-config/pkg/commands.cmdInfo(0xc4200ba500, 0x0, 0x0)
        /private/tmp/assh-20160927-71842-9d3aw8/advanced-ssh-config-2.4.1/src/github.com/moul/advanced-ssh-config/pkg/commands/info.go:20 +0x9bd
reflect.Value.call(0x4236c00, 0x429fbb0, 0x13, 0x428095d, 0x4, 0xc42004b830, 0x1, 0x1, 0x4081898, 0x42777c0, ...)
        /usr/local/Cellar/go/1.7.1/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x4236c00, 0x429fbb0, 0x13, 0xc42004b830, 0x1, 0x1, 0xc420075da0, 0x140, 0x140)
        /usr/local/Cellar/go/1.7.1/libexec/src/reflect/value.go:302 +0xa4
github.com/moul/advanced-ssh-config/vendor/github.com/codegangsta/cli.HandleAction(0x4236c00, 0x429fbb0, 0xc4200ba500, 0x0, 0x0)
        /private/tmp/assh-20160927-71842-9d3aw8/advanced-ssh-config-2.4.1/src/github.com/moul/advanced-ssh-config/vendor/github.com/codegangsta/cli/app.go:481 +0x1e0
github.com/moul/advanced-ssh-config/vendor/github.com/codegangsta/cli.Command.Run(0x4280ad9, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4288fd9, 0x1f, 0x0, ...)
        /private/tmp/assh-20160927-71842-9d3aw8/advanced-ssh-config-2.4.1/src/github.com/moul/advanced-ssh-config/vendor/github.com/codegangsta/cli/command.go:186 +0xc26
github.com/moul/advanced-ssh-config/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200ce180, 0xc420084060, 0x2, 0x2, 0x0, 0x0)
        /private/tmp/assh-20160927-71842-9d3aw8/advanced-ssh-config-2.4.1/src/github.com/moul/advanced-ssh-config/vendor/github.com/codegangsta/cli/app.go:235 +0x60c
main.main()
        /private/tmp/assh-20160927-71842-9d3aw8/advanced-ssh-config-2.4.1/src/github.com/moul/advanced-ssh-config/cmd/assh/main.go:48 +0x44b
```

**Comment by moul** [comment]
Hi @tdi, thank you for your feedback,

Can you give me the result of `assh version` ?

**Comment by tdi** [comment]
Hey @moul this what I have, brew installed.
`assh version 2.4.1 (HEAD)`

**Comment by moul** [comment]
Hi @tdi, I just released a new version here: https://github.com/moul/advanced-ssh-config/releases/tag/v2.5.0

It contains a patch for your issue

Thanks again for your feedback

**Comment by tdi** [comment]
I confirm that it is fixed ! 👌
